### ISSUE TITLE
Any pre built release available?

### ISSUE THREAD

**Issue by mvadu** [chkr1011/MQTTnet.App#1]
Hello, just starting with MQTTnet library. So was wondering if you have published any pre built binaries for Windows or linux anywhere? Or its just source and we have to figure out how to build in our favorite OS?

**Comment by jhalbrecht** [comment]
Sorry, I have not included binaries in the repo. This project builds for Win 10 UWP, and Android. I haven't tested the ios.

**Comment by chkr1011** [comment]
Hi,

sorry but the app is not stable enough to release a version yet but I will release some preview builds soon.
If you want to contribute and speed up things please let me know.

Best regards
Christian

**Comment by ln-12** [comment]
Hey @chkr1011, are there any updates on this?

**Comment by chkr1011** [comment]
Sorry no update yet. I am mostly working on MQTTnet. After the next major release I will focus on this project again. But if you want you can create a pull request which includes scripts for creating the packages etc.

**Comment by chkr1011** [comment]
Now the first prerelease builds are available.
