### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by codec-abc** [chkr1011/MQTTnet.App#2]
Hi.

This is not a real issue, but I just wanted to say thanks for that app 👍 .

I wanted a GUI that make easy to send and receive MQTT messages and your app just do that perfectly. Before that I used MQTTBox but when sending a few hundred messages in a few milliseconds it become really slow while your app remain responsive.

So thanks a lot for this.

**Comment by jhalbrecht** [comment]
Hi @codec-abc Thank you for this comment. I'm glad someone found the example useful, as was my intent.

**Comment by chkr1011** [comment]
Hi, 
thank you for your feedback! I am still working on this app and hope to release new versions soon. 
If you want to contribute please let me know.

Best regards
Christian
