### ISSUE TITLE
The app crashes

### ISSUE THREAD

**Issue by INTERNALINTERFERENCE** [chkr1011/MQTTnet.App#5]
The connection is closed if a large amount of data gets into the listbox.
You can check it by entering this data in the options: **host**: test.mosquitto.org **port**: 1883

**Comment by INTERNALINTERFERENCE** [comment]
and try to subscribe "#"

**Comment by INTERNALINTERFERENCE** [comment]
https://github.com/reactivemarbles/DynamicData 
you can use this instead of list

**Comment by chkr1011** [comment]
In my opinion there should be some sort of virtualization happening or at least a proper filter or maximum amount of entries in the list. I do not think that these extension will solve the problem because it is a problem in Avalonia UI. I will have a look how to solve that issue.

**Comment by INTERNALINTERFERENCE** [comment]
OK, I will wait for the solution of the problem

**Comment by chkr1011** [comment]
I assume this one can be closed because it is no longer an issue.
